FROM python:3.8

WORKDIR /code

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY models models
COPY test/test.py .

RUN python -m unittest test.TestModels

COPY src/ .

# command to run on container start
ENTRYPOINT [ "python", "./test.py" ]
